[package]
name = "fsh"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = {version="1.0.197", features=["derive"]}
serde_json = "1.0.114"
libc = "0.2.153"
glob = "0.3.1"
clap = {version = "4", features = ["derive"]}

[profile.dev]
opt-level = 0
debug = true